"""empty message

Revision ID: 26d4e76e1e02
Revises: 
Create Date: 2019-10-07 01:05:02.699021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d4e76e1e02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moral_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_mother_last_name', sa.String(), nullable=True),
    sa.Column('legal_father_last_name', sa.String(), nullable=True),
    sa.Column('legal_first_name', sa.String(), nullable=True),
    sa.Column('legal_second_name', sa.String(), nullable=True),
    sa.Column('legal_birthday', sa.String(), nullable=True),
    sa.Column('legal_gender', sa.String(), nullable=True),
    sa.Column('legal_birth_country', sa.String(), nullable=True),
    sa.Column('legal_birth_state', sa.String(), nullable=True),
    sa.Column('legal_nationality', sa.String(), nullable=True),
    sa.Column('legal_curp', sa.String(), nullable=True),
    sa.Column('legal_tel', sa.String(), nullable=True),
    sa.Column('legal_email', sa.String(), nullable=True),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('business_rfc', sa.String(), nullable=True),
    sa.Column('business_address_type', sa.String(), nullable=True),
    sa.Column('business_zipcode', sa.String(), nullable=True),
    sa.Column('business_state', sa.String(), nullable=True),
    sa.Column('business_county', sa.String(), nullable=True),
    sa.Column('business_neighborhood', sa.String(), nullable=True),
    sa.Column('business_city', sa.String(), nullable=True),
    sa.Column('business_street', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('id_cliente', sa.String(), nullable=True),
    sa.Column('numero_cuenta_evva', sa.String(), nullable=True),
    sa.Column('clabe', sa.String(), nullable=True),
    sa.Column('fecha_apertura', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moral_persons')
    # ### end Alembic commands ###
